# fly.toml app configuration file generated for yolov8-onnxruntime-rust on 2023-12-02T00:05:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yolov8-onnxruntime-rust"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
