[package]
name = "river-zmq-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
rand = "0.8.5"
tmq = "0.4.0"
tokio = { version = "1.34.0", features = ["full"] }
zmq = "0.10.0"
